services:
  - type: web
    name: fileinclusion-demo
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn fileinclusion_demo.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: fileinclusion_demo.settings
